### ISSUE TITLE
Noncompliant with official Hardware API

### ISSUE THREAD

**Issue by cdisselkoen** [keyboardio/Kaleidoscope-Model01-TestMode#3]
This plugin uses a lot of features of Hardware-Model01 that aren't a part of the official Hardware API.  This breaks builds for other hardwares, for any sketches that include Model01-TestMode.

Unclear to me whether the solution is inside this plugin, or just that sketches containing TestMode should mark themselves as Model01-only or something.

**Comment by algernon** [comment]
This plugin was specifically made for the Model01, so it breaking with other hardware modules is to be expected, in my opinion. We should probably make that clear, and error out if the plugin is being compiled for anything else but the Model01. I'll prep a PR doing so.
